apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceanalyzer-frontend
  labels:
    app: faceanalyzer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faceanalyzer-frontend
  template:
    metadata:
      labels:
        app: faceanalyzer-frontend
    spec:
      containers:
      - name: faceanalyzer-frontend
        image: plavy/faceanalyzer-frontend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: faceanalyzer-frontend
spec:
  selector:
    app: faceanalyzer-frontend
  ports:
    - protocol: TCP
      name: faceanalyzer-frontend
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faceanalyzer-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - staging.faceanalyzer.plavy.me
      secretName: staging.faceanalyzer.plavy.me-tls
  rules:
  - host: staging.faceanalyzer.plavy.me
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: faceanalyzer-frontend
            port:
              number: 80
