name: Build and Deploy

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: face-analyzer
    steps:
    - uses: actions/checkout@v3
    - name: Add Visage SDK License file
      uses: mobiledevops/secret-to-file-action@v1
      with:
        base64-encoded-secret: ${{ secrets.VISAGE_SDK_LICENSE }}
        filename: "728-647-708-712-368-939-525-416-088-964-238.vlc"
        working-directory: face-analyzer/public
    - name: Set the License
      run: grep -rli '416-088-305-748.vlc' * | xargs -i@ sed -i 's/416-088-305-748.vlc/416-088-964-238.vlc/g' @
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag plavy/faceanalyzer-frontend:${{ github.sha }}
    - name: Push the Docker image
      run: docker push plavy/faceanalyzer-frontend:${{ github.sha }}
  deploy:
    name: Deploy frontend
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: main
      url: https://faceanalyzer.plavy.me/
    defaults:
      run:
        working-directory: face-analyzer
    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    steps:
    - name: Apply manifest
      uses: actions-hub/kubectl@master
      with:
        args: apply -n faceanalyzer -f manifest.yaml
    - name: Set image tag
      uses: actions-hub/kubectl@master
      with:
        args: set image -n faceanalyzer deployment/faceanalyzer-frontend faceanalyzer-frontend=plavy/faceanalyzer-frontend:${{ github.sha }}
